language: node_js
node_js:
  - 16.3
services:
  - docker
cache:
  directories:
    - node_modules
before-install:
  - npm install -g codecov
  - docker pull e89835/rehabtime
before-script:
  - docker run -d -p 127.0.0.1:80:3000 e89835/rehabtime /bin/sh -c "npm run start"
script:
  - docker ps -a
  - docker stop -t 15
  - docker run e89835/rehabtime /bin/sh -c "npm test"
#after_success:
#  - docker-compose down
