name: GitHub Container Registry Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login 2 GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
      
    - name: Build & Push the Docker image GHCR
      uses: docker/build-push-action@v2
      with: 
        push: true
        tags: ghcr.io/${{ secrets.DOCKER_USERNAME }}/rehabtime:latest
